# Generated by Django 5.2.3 on 2025-07-02 15:43

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('item', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=home.models.unique_image_path)),
                ('product_id', models.IntegerField(editable=False, unique=True)),
                ('price', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=25)),
            ],
        ),
    ]
