# Generated by Django 5.2.3 on 2025-07-08 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
