# Generated by Django 5.2.3 on 2025-07-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='product_id',
            field=models.IntegerField(unique=True),
        ),
    ]
